language: c
os:
    - linux
addons:
    apt:
        packages:
            - autoconf
            - autoconf2.64
            - automake
            - libtool
            - m4
            - texinfo
            - makeinfo
            - libgmp-dev
            - libmpfr-dev
            - libmpc-dev
script:
    - make -j3 fetch
    - make -kj3 all
