language: c
os:
    - linux
sudo:
    required
addons:
    apt:
        packages:
            - autoconf
            - autoconf2.64
            - automake
            - libtool
            - m4
            - texinfo
            - makeinfo
            - libgmp-dev
            - libmpfr-dev
            - libmpc-dev
script:
    - sudo apt-get install autoconf2.13 automake clang libtool m4 texinfo libgmp-dev libmpfr-dev libmpc-dev binutils yasm
    - (CC=clang make -kj3 build/spidermonkey.make >/dev/null 2>/dev/null) || CC=clang make -kj3 build/spidermonkey.make
    - make -kj3 build/spidermonkey.clean
    - (sleep 5m && echo "I'm not done yet") &
    - (sleep 10m && echo "I'm not done yet") &
    - (sleep 15m && echo "I'm not done yet") &
    - (sleep 20m && echo "I'm not done yet") &
    - (sleep 25m && echo "I'm not done yet") &
    - (sleep 30m && echo "I'm not done yet") &
    - (PATH=/usr/local/bin:/usr/bin:/bin make -kj3 build/binutils-gdb.make >/dev/null 2>/dev/null) || PATH=/usr/local/bin:/usr/bin:/bin make -kj3 build/binutils-gdb.make
    - (PATH=/usr/local/bin:/usr/bin:/bin make -kj3 build/gcc-preliminary.make >/dev/null 2>/dev/null) || PATH=/usr/local/bin:/usr/bin:/bin make -kj3 build/gcc-preliminary.make
    - (PATH=/usr/local/bin:/usr/bin:/bin make -kj3 build/glibc.make >/dev/null 2>/dev/null) || PATH=/usr/local/bin:/usr/bin:/bin make -kj3 build/glibc.make
    - (PATH=/usr/local/bin:/usr/bin:/bin make -kj3 build/gcc-final.make >/dev/null 2>/dev/null) || PATH=/usr/local/bin:/usr/bin:/bin make -kj3 build/gcc-final.make
    - make -kj3 build/perl.make
