language: c
os:
    - linux
sudo: required
addons:
    apt:
        packages:
            - autoconf
            - autoconf2.13
            - automake
            - clang
            - libtool
            - m4
            - texinfo
            - libgmp-dev
            - libmpfr-dev
            - libmpc-dev
script:
    - sudo apt-get install autoconf2.13 yasm
    - (sleep 5m && echo "I'm not done yet") &
    - (sleep 10m && echo "I'm not done yet") &
    - (sleep 15m && echo "I'm not done yet") &
    - (sleep 20m && echo "I'm not done yet") &
    - make -kj3 build/binutils-gdb.make
    - make -kj3 build/gcc-preliminary.make
