language: c
os:
    - linux
sudo: required
script:
    - sudo apt-get install autoconf2.13 automake clang libtool m4 texinfo libgmp-dev libmpfr-dev libmpc-dev binutils
    - PATH=/usr/local/bin:/usr/bin:/bin make -kj3 build/binutils-gdb.make
    - PATH=/usr/local/bin:/usr/bin:/bin make -kj3 build/gcc-preliminary.make
