language: c
os:
    - linux
sudo: required
addons:
    apt:
        packages:
            - autoconf
            - autoconf2.13
            - automake
            - clang
            - libtool
            - m4
            - texinfo
            - libgmp-dev
            - libmpfr-dev
            - libmpc-dev
script:
    - sudo apt-get install autoconf2.13 yasm
    - (sleep 5m && echo "I'm not done yet") &
    - (sleep 10m && echo "I'm not done yet") &
    - (sleep 15m && echo "I'm not done yet") &
    - (sleep 20m && echo "I'm not done yet") &
    - (CC=clang make -kj3 build/spidermonkey.make >/dev/null 2>/dev/null) || CC=clang make -kj3 build/spidermonkey.make
    - make -kj3 build/spidermonkey.clean
    - (make -kj3 build/binutils-gdb.make >/dev/null 2>/dev/null) || make -kj3 build/binutils-gdb.make
    - (make -kj3 build/gcc-preliminary.make >/dev/null 2>/dev/null) || make -kj3 build/gcc-preliminary.make
    - (make -kj3 build/glibc.make >/dev/null 2>/dev/null) || make -kj3 build/glibc.make
    - (make -kj3 build/gcc-final.make >/dev/null 2>/dev/null) || make -kj3 build/gcc-final.make
    - make -kj3 build/ncurses.make
    - make -kj3 build/emacs.make
