language: c
compiler:
    - gcc
os:
    - linux
addons:
    apt:
        packages:
            - autoconf
            - automake
            - libtool
            - m4
script:
    - make fetch
    - make all
