language: c
os:
    - linux
sudo: required
script:
    - sudo apt-get install autoconf2.13 yasm automake clang libtool m4 texinfo libgmp-dev libmpfr-dev libmpc-dev gcc-5 binutils
    - make -kj3 build/binutils-gdb.make
    - make -kj3 build/gcc-preliminary.make
