language: c
compiler:
    - gcc
os:
    - linux
addons:
    apt:
        packages:
            - autoconf
            - automake
            - libtool
            - m4
script:
    - make -j3 fetch
    - make -j3 all
